from typing import Protocol

class CoffeeRepository(Protocol):
    async def search(self, filters: dict) -> list[dict]: ...
    async def create(self, product: dict) -> dict: ...

class ConversationRepository(Protocol):
    async def get_context(self, customer_id: str) -> dict: ...
    async def save_context(self, customer_id: str, context: dict) -> None: ...
